/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://vhtsthacijhh5a4pbpwpdc3xgm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xedf6pp4djd23inyutovujeqe4",
    "aws_cognito_identity_pool_id": "us-east-1:3e03e025-9d85-4012-b644-5abbce0628a7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2LSdBcOP9",
    "aws_user_pools_web_client_id": "7qn21hdoh15f517hl4s1c1aon8",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 7,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "allogroup1a63836cdcbb4c7db397ea7cee38cd34213348-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
